### ISSUE TITLE
Class MyApp\LoopController not found.

### ISSUE THREAD

**Issue by ThePureCC** [agougousis/ratchet-sample#1]
installed Ratchet with composer on /home/rac

when running launcher.php, this error comes back:

$ php launcher.php
PHP Fatal error:  Class 'MyApp\LoopController' not found in /home/rac/launcher.php on line 8

file structure is like this:

/home/rac/launcher.php
/home/rac/vendor/
/home/rac/MyApp/src/MyApp/LoopController.php
/home/rac/MyApp/src/MyApp/Pusher.php

Am I doing something wrong?

**Comment by agougousis** [comment]
Have you adjusted the path to the autoload file in launcher.php ?

**Comment by ThePureCC** [comment]
@agougousis  

Thanks for the reply, I did adjust the path. Your code is the only example that at least gave me an error(others stuck at $php launcher.php without executing anything, other than hangs there.) I gave up on Ratchet as a whole last night, and went with another library. 

Sorry if I had wasted your time.

**Comment by agougousis** [comment]
No problem, man! It's been long since I dealt with Ratchet. Anyway, with a first look, it seems that there is something wrong with your application structure (paths, namespaces,...). If you are interested to give Ratchet a try (even if you went with another library), I can take some time tomorrow and send you exact steps on how you can set it up.

**Comment by ThePureCC** [comment]
I really appreciate the offer, but I think with my skill level, I'm gonna leave Ratchet for now.

With Rachet's documentation, I can already imagine I would need tons of help even if I set it up properly :]

**Comment by agougousis** [comment]
All right! If you ever feel you are ready to have a look behind the curtains and get some basic understand on how async is achieved with these libraries, you can have a look here: https://blog.gougousis.net/the-inner-workings-of-an-event-loop-the-reactphp-case/

**Comment by ThePureCC** [comment]
Thanks! Reading it right now.
