### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by hpng6** [agougousis/ratchet-sample#2]
Hi,

i'm getting server status "off". whats wrong with me. could you please help me
![Screen Shot 2019-07-08 at 7 23 17 PM](https://user-images.githubusercontent.com/16951742/60815738-e256c280-a1b5-11e9-95f4-e6aeb7d64a56.png)

**Comment by agougousis** [comment]
Hi! Is all the code there or you forgot to run "composer install" ?  :-)

**Comment by hpng6** [comment]
Yes i run the composer, got the vendor folder along with autoload.php.

**Comment by agougousis** [comment]
And it is not working ?
Please, give some more insight. Since you are using Docker, why you are using "localhost/new_socket/client.html" and not "localhost/client.html" ?
Are you running other web servers, too, locally (e.g XAMP) ?
